---
- name: Add software repository keys
  apt_key:
    state: present
    url: '{{item}}'
  become: yes
  with_items:
    - https://dl.yarnpkg.com/debian/pubkey.gpg
    - https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add software repositories
  apt_repository:
    state: present
    repo: '{{item}}'
    update_cache: True
  become: yes
  with_items:
    - deb https://dl.yarnpkg.com/debian/ stable main
    - deb https://deb.nodesource.com/node_14.x buster main

- name: Install packages
  apt:
    name:
      - nodejs
      - yarn
      - build-essential
    state: present
  become: yes
